name: Deploy Documentation

on:
  workflow_dispatch:

jobs:
  docs:
    uses: scikit-package/release-scripts/.github/workflows/_publish-docs-on-release.yml@v0
    with:
      project: scikit-package-manuscript
      c_extension: false
      headless: false
